// Code generated by hwygen. DO NOT EDIT.

package s2

import (
	"os"
	"simd/archsimd"
)

var PlateCarreeProject func(lats, lngs, xs, ys []float32, fromRadians float32)
var PlateCarreeProjectFloat64 func(lats, lngs, xs, ys []float64, fromRadians float64)
var MercatorProject func(lats, lngs, xs, ys []float32, fromRadians float32)
var MercatorProjectFloat64 func(lats, lngs, xs, ys []float64, fromRadians float64)

func init() {
	if os.Getenv("HWY_NO_SIMD") != "" {
		initFallback()
		return
	}
	if archsimd.X86.AVX2() {
		initAVX2()
		return
	}
	initFallback()
}

func initAVX2() {
	PlateCarreeProject = BasePlateCarreeProject_avx2
	PlateCarreeProjectFloat64 = BasePlateCarreeProject_avx2_Float64
	MercatorProject = BaseMercatorProject_avx2
	MercatorProjectFloat64 = BaseMercatorProject_avx2_Float64
}

func initFallback() {
	PlateCarreeProject = BasePlateCarreeProject_fallback
	PlateCarreeProjectFloat64 = BasePlateCarreeProject_fallback_Float64
	MercatorProject = BaseMercatorProject_fallback
	MercatorProjectFloat64 = BaseMercatorProject_fallback_Float64
}
