// Code generated by hwygen. DO NOT EDIT.

package s2

import (
	"github.com/ajroetker/go-highway/hwy"
	"github.com/ajroetker/go-highway/hwy/contrib/math"
)

func BasePlateCarreeProject_fallback(lats, lngs, xs, ys []float32, fromRadians float32) {
	size := min(len(lats), len(lngs))
	vFromRad := hwy.Set(fromRadians)
	for ii := 0; ii < size; ii += vFromRad.NumLanes() {
		lat := hwy.Load(lats[ii:])
		lng := hwy.Load(lngs[ii:])
		y := hwy.Mul(lat, vFromRad)
		x := hwy.Mul(lng, vFromRad)
		hwy.Store(y, ys[ii:])
		hwy.Store(x, xs[ii:])
	}
}

func BasePlateCarreeProject_fallback_Float64(lats, lngs, xs, ys []float64, fromRadians float64) {
	size := min(len(lats), len(lngs))
	vFromRad := hwy.Set(fromRadians)
	for ii := 0; ii < size; ii += vFromRad.NumLanes() {
		lat := hwy.Load(lats[ii:])
		lng := hwy.Load(lngs[ii:])
		y := hwy.Mul(lat, vFromRad)
		x := hwy.Mul(lng, vFromRad)
		hwy.Store(y, ys[ii:])
		hwy.Store(x, xs[ii:])
	}
}

func BaseMercatorProject_fallback(lats, lngs, xs, ys []float32, fromRadians float32) {
	size := min(len(lats), len(lngs))
	vFromRad := hwy.Set(fromRadians)
	vHalf := hwy.Set(float32(0.5))
	vOne := hwy.Set(float32(1.0))
	vYScale := hwy.Mul(vHalf, vFromRad)
	for ii := 0; ii < size; ii += vFromRad.NumLanes() {
		lng := hwy.Load(lngs[ii:])
		x := hwy.Mul(lng, vFromRad)
		hwy.Store(x, xs[ii:])
		lat := hwy.Load(lats[ii:])
		s := math.Sin(lat)
		num := hwy.Add(vOne, s)
		den := hwy.Sub(vOne, s)
		val := hwy.Div(num, den)
		l := math.Log(val)
		y := hwy.Mul(l, vYScale)
		hwy.Store(y, ys[ii:])
	}
}

func BaseMercatorProject_fallback_Float64(lats, lngs, xs, ys []float64, fromRadians float64) {
	size := min(len(lats), len(lngs))
	vFromRad := hwy.Set(fromRadians)
	vHalf := hwy.Set(float64(0.5))
	vOne := hwy.Set(float64(1.0))
	vYScale := hwy.Mul(vHalf, vFromRad)
	for ii := 0; ii < size; ii += vFromRad.NumLanes() {
		lng := hwy.Load(lngs[ii:])
		x := hwy.Mul(lng, vFromRad)
		hwy.Store(x, xs[ii:])
		lat := hwy.Load(lats[ii:])
		s := math.Sin(lat)
		num := hwy.Add(vOne, s)
		den := hwy.Sub(vOne, s)
		val := hwy.Div(num, den)
		l := math.Log(val)
		y := hwy.Mul(l, vYScale)
		hwy.Store(y, ys[ii:])
	}
}
